# Generated by Django 2.2.7 on 2019-12-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191203_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
