# Generated by Django 2.2.7 on 2019-12-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20191203_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
